# -*- mode: ruby -*-
# vi: set ft=ruby :

# Проверяем наличие плагина "vagrant-reload"
unless Vagrant.has_plugin?("vagrant-reload")
  raise 'vagrant-reload is not installed! Please install it and try again.'
end



Vagrant.configure(2) do |config|
  # Работает только с vagrant-vbguest 0.21, поэтому запрещаем обновляться
  if Vagrant.has_plugin?("vagrant-vbguest") then
      config.vbguest.auto_update = false
  end

  # Скачиваем box для Vagrant
  config.vm.box = "centos/7"

  # Устанавливаем связь портов физической и вирутальной машины. 
  # Сайт будет доступен по адресу localhost:8888/ 
  # Для соединения с базой используйте порт 8889
  config.vm.network :forwarded_port, guest: 80, host: 8888, auto_correct: true
  config.vm.network :forwarded_port, guest: 3306, host: 8889, auto_correct: true
  config.vm.network :forwarded_port, guest: 5432, host: 5433, auto_correct: true

  config.ssh.insert_key = false
  
  # Синхронизируем папки на виртуальной и физической машине
  # config.vm.synced_folder "../", "/home/bitrix/"

  
  # Определяем 2ГБ ОЗУ
  ram_volume = 2048
  # Определяем кол-во ядер для процессора вручную (актуально для Windows)
  cpu_count = 4
  # Если Linux или MacOS то получаем все доступные ядра в хост-системе 
  if RUBY_PLATFORM =~ /linux/
    cpu_count = `nproc`.to_i
  elsif RUBY_PLATFORM =~ /darwin/
    cpu_count = `sysctl -n hw.ncpu`.to_i
  end

  # Непосредственно прокидываем настройки "железа" в виртуальную машину 
  config.vm.provider :virtualbox do |vb|
      vb.customize [
        "modifyvm", :id, 
        "--memory", 
        [ENV['DISCOURSE_VM_MEM'].to_i, 2048].max
      ]
      vb.customize ["modifyvm", :id, "--cpus", cpu_count]
  end

  # Устанавливаем виртуальную машину битрикс
  config.vm.provision :shell, path: "install.bash"
  config.vm.provision :reload
  config.vm.provision :shell, path: "install_after_reload.bash"
  config.vm.provision :shell, inline: "hostname"

  # 
  config.ssh.keys_only = false
  config.ssh.username = "test"
  config.ssh.password = "test"
  config.ssh.connect_timeout = 4
end
